version: "3"
services:
  php-fpm:
    image: php:7.3.9-fpm-alpine
    working_dir: /application
    volumes:
      - ./:/application/source
      - ./var:/application/var
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
