services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    JTL\SCX\Lib\Channel\Core\Command\AbstractCommand:
      tags: ['console.command']
    JTL\Nachricht\Contract\Listener\Listener:
      public: true

  Psr\Log\LoggerInterface: '@Monolog\Logger'

  JTL\Nachricht\Contract\Emitter\Emitter: '@JTL\Nachricht\Emitter\AmqpEmitter'

  JTL\SCX\Channel\SignUpController:
    public: true

  # DI Setup - if you change the namespace of your project
  # consider to change the namespace below to a working DI container

  JTL\SCX\Channel\:
    resource: '../src/*'

  # Meta Data Services

  JTL\SCX\Lib\Channel\Contract\MetaData\MetaCategoryLoader: '@JTL\SCX\Channel\Demo\MetaData\CategoryTreeLoader'

  JTL\SCX\Lib\Channel\Contract\MetaData\MetaDataAttributeLoader: '@JTL\SCX\Channel\Demo\MetaData\Attribute\CategoryAttributeLoader'

  # JTL\SCX\Lib\Channel\Contract\MetaData\SellerAttributeLoader:
  #   class: JTL\SCX\Channel\MetaData\Attribute\SellerAttributeLoader

  # Add your additional services below




